image: "registry.gitlab.si.francetelecom.fr/mdcs/expapp/docker/ci/php-composer:7.0-xenial"
variables:
  ARTI_REPO: "https://artifactory.packages.install-os.multis.p.fti.net/sfy-mdcs_composer/slim-bootstrap"

.add_ssh_private_key_template:
  before_script: &add_ssh_private_key
  - eval $(ssh-agent -s)
  - ssh-add <(echo -e "$SSH_PRIVATE_KEY")

stages:
  - prepare
  - test
  - package

prepare:dist:
  stage: prepare
  tags:
    - search
  before_script: *add_ssh_private_key
  script:
    - composer install --no-dev -o
  artifacts:
    paths:
      - src
      - vendor
    expire_in: '2 hours'

prepare:dev:
  stage: prepare
  tags:
    - search
  before_script: *add_ssh_private_key
  script:
    - composer install
  artifacts:
    paths:
      - src
      - bin
      - tests
      - vendor
    expire_in: '2 hours'

test:static:
  stage: test
  tags:
    - search
  script:
    - composer phpcs
  dependencies:
    - prepare:dev

test:tu:
  stage: test
  tags:
    - search
  script:
    - composer phpunit
  dependencies:
    - prepare:dev

package:composer:
  stage: package
  tags:
  - search
  script:
  - publish-composer "${ARTI_KEY}" "${ARTI_REPO}" "${CI_COMMIT_TAG}"
  only:
  - tags
